language: go

go:
  - 1.18
  - 1.19
  - 1.20
  - 1.21
  - 1.22
  - 1.23

before_install:
  - go install github.com/mattn/goveralls@latest
  - go install golang.org/x/tools/cmd/cover@latest

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci

notifications:
  email: false
